"""Subclass of RcFrame, which is generated by wxFormBuilder."""

import wx
import RcCode
import IrRemoteControl

# Implementing RcFrame
class irRemoteControlRcFrame( RcCode.RcFrame ):
	playSpeed = 0
	checker = None

	def __init__( self, parent, irRemote ):
		RcCode.RcFrame.__init__( self, parent )
		self.irrc = irRemote

	def setSessionTime(self, sessionTimeSeconds):
		sessionTime = wx.DateTime.FromTimeT(sessionTimeSeconds)
		self.session_time_pick.SetValue(sessionTime.Subtract(wx.TimeSpan(1)))
	

	# Handlers for RcFrame events.
	def handle_keypress( self, event ):
		print("Key: " + str(event.GetKeyCode()))
		pass

	def frLeftDown( self, event ):
		if self.playSpeed >= 0:
			self.playSpeed = -2
		elif self.playSpeed < 0:
			self.playSpeed *= 2

		self.irrc.updatePlaySpeed(self.playSpeed, False)
		event.Skip()

	def lfLeftDown( self, event ):
		self.irrc.updateShownFrame(-2)
		event.Skip()

	def ppLeftDown( self, event ):
		if self.playSpeed == 0:
			self.playSpeed = 1
		else:
			self.playSpeed = 0

		self.irrc.updatePlaySpeed(self.playSpeed, False)
		event.Skip()

	def nfLeftDown( self, event ):
		self.irrc.updateShownFrame(2)
		event.Skip()

	def ffLeftDown( self, event ):
		if self.playSpeed <= 0:
			self.playSpeed = 2
		elif self.playSpeed > 0:
			self.playSpeed *= 2

		self.irrc.updatePlaySpeed(self.playSpeed, False)
		event.Skip()

	def liveLeftDown( self, event ):
		self.irrc.toLivePosition()
		event.Skip()

	def camCase( self, event ):
		self.irrc.camSwitch('Chase')
		event.Skip()

	def camFarChase( self, event ):
		self.irrc.camSwitch('Far Chase')
		event.Skip()

	def camRearChase( self, event ):
		self.irrc.camSwitch('Rear Chase')
		event.Skip()

	def camCockpit( self, event ):
		self.irrc.camSwitch('Cockpit')
		event.Skip()

	def setTimePosition( self, event ):
		irSessionTime = event.GetDate().GetHour() * 3600
		irSessionTime += event.GetDate().GetMinute() * 60
		irSessionTime += event.GetDate().GetSecond()
		self.irrc.setTimePosition(irSessionTime)
		event.Skip()

	def closeWindow( self, event ):
		self.checker.sentinel = False
		event.Skip()

